export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE'

export const DETAIL_ITEM_REQUEST = 'DETAIL_ITEM_REQUEST'
export const DETAIL_ITEM_SUCCESS = 'DETAIL_ITEM_SUCCESS'
export const DETAIL_ITEM_FAILURE = 'DETAIL_ITEM_FAILURE'

export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE'

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE'

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE'

export const SEARCH_ITEM_REQUEST = 'SEARCH_ITEM_REQUEST'
export const SEARCH_ITEM_SUCCESS = 'SEARCH_ITEM_SUCCESS'
export const SEARCH_ITEM_FAILURE = 'SEARCH_ITEM_FAILURE'

export const UPLOADFILE_ITEM_REQUEST = 'UPLOADFILE_ITEM_REQUEST'
export const UPLOADFILE_ITEM_SUCCESS = 'UPLOADFILE_ITEM_SUCCESS'
export const UPLOADFILE_ITEM_FAILURE = 'UPLOADFILE_ITEM_FAILURE'

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'
export const CLEAR_ITEM = 'CLEAR_ITEM'